### ISSUE TITLE
Issues editing theme.js

### ISSUE THREAD

**Issue by M0nica** [melangue/dactl#10]
I am having trouble adjusting the css for the theme. I have changed the `--text-color` and `--link-color` to lime in `theme.js` and both are still appearing as black whenever I load the website. I have tried restarting the server and clearing the cache. Do you have any suggestions?

```
const LightTheme = {
  '--bg-color': '#eee',
  '--text-color': '#8BC34A',
  '--text-color-light': '#828282',
  '--link-color': '#8BC34A',
  '--metadata-color': '#999',
  '--post-title': '#313131',
  '--code-bg-color': '#fff',
  '--code-border': '#f5f5f5',
  '--table-border-color': '#e5e5e5',
  '--table-header-color': '#fefefe',
  '--shadow-color': 'rgba(0, 0, 0, 0.1)',
  '--invert-logo-color': 'invert(0)',
  themeName: 'LightTheme'
}
```

I believe I followed the instructions according to the README

> Theme switcher
> Theme switcher is made in vanilla Javascript and works using CSS Variables. Values (colors) specified for each variable are injected into :root on every page load.
> User theme choice is saved in browser's Local Storage and is persistent through sessions.
> 
> You can edit the colors of both Light and Dark themes in theme.js file found in _assets/js/.

**Comment by M0nica** [comment]
It seems to resolve when I flip the theme from light to dark.

Seems to be related to the issue that was referenced on the README.

>  Fix theme-switcher - sometimes it does not inject all of the colors properly on first page load and a refresh, fixes itself after switching the theme back and forth.

**Comment by nicnic-cc** [comment]
You're right, it's the theme-switcher's fault. I have take a look if it's even fixable.
