### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by tristanfcraig** [melangue/dactl#12]
How can I go about editing the way dates format to the American system Month/Day/Year?

**Comment by nicnic-cc** [comment]
You need to edit two files - `blog.html` and `post.html` which are located within `_includes` folder.  

Look for this: 
`<span>{{ post.date | date: "%d/%m/%Y" }}</span>`

Change to this:
`<span>{{ post.date | date: "%m/%d/%Y" }}</span>`

And that's it. Sorry for the late reply.
