### ISSUE TITLE
Cant solve some issues about theme

### ISSUE THREAD

**Issue by dkarthe** [melangue/dactl#3]
Hi,
I installed on your theme into my site, its running normally, I want suggest to add some extra features like,

1. Custom logo (can't modified) not supported to( jpg & png) 
2. To add new menu
3. How to place post custom images.
4. How to place hero images. normally when I place unsplash collection images, it won't reflect on post.
5. Can't implement new social icons on head section.

**Comment by rossmuego** [comment]
Yeah I too feel like these would be good additions, especially the social logos.

**Comment by nicnic-cc** [comment]
Hi, 
Thanks for your comment and sorry about late reply.

1. That seems doable, I'll think about that
2. What do you mean by 'new menu'?
3. Do you mean attaching images inside your posts?
4. Look at the YAML frontmatter on sample posts - you need to include `hero: https://someaddress.com/someimage.jpg` for it to work properly
5. What social icons are you missing?
