### ISSUE TITLE
Undesired class="highlight"> appearing on blog posts

### ISSUE THREAD

**Issue by matheuscandido** [melangue/dactl#4]
I just forked the repo and this error of a class="highlight"> keeps appearing every time code or any other highlighted text is on the body of a post.
Look:
![screen shot 2017-10-21 at 15 28 49](https://user-images.githubusercontent.com/1309911/31854279-cb04c8e4-b674-11e7-99b4-9732742bf9cc.png)

**Comment by tribut** [comment]
This is due to a too recent version of rouge. Fixed in https://github.com/melangue/dactl/pull/2, specifically https://github.com/melangue/dactl/commit/2be5b2353b7589ff9a84e76d2b3af145691ce27c

**Comment by nicnic-cc** [comment]
Fixed in #2
